### ISSUE TITLE
Todo application in HTML,CSS and JavaScript and Node.js as backend with image upload support

### ISSUE THREAD

**Issue by Samihan15** [Git21221/JS-beginner-projects#113]
@Git21221  can you please assign this task under hacktoberfest label.

**Comment by Git21221** [comment]
@Samihan15 THERE is a to do application in our repo....can you make changes on it?

**Comment by Samihan15** [comment]
sure !

**Comment by Git21221** [comment]
@Samihan15 great

**Comment by Samihan15** [comment]
Hello @Git21221 I have made a PR
