### ISSUE TITLE
Project to demonstrate to authentication of users in Node.Js and Express.Js using APIs

### ISSUE THREAD

**Issue by Samihan15** [Git21221/JS-beginner-projects#120]
@Git21221 please assign this task under hacktoberfest label

**Comment by Git21221** [comment]
please elaborate

**Comment by Samihan15** [comment]
@Git21221 it's a web app having login page, sign up page, home page and about it page.
I have created APIs using Node.js and express which uses cookies. and also the user information will store in json file format (can use mongoDB too) so if you allow I will post some issues regarding enhancement like improving the ui of home page .

**Comment by Git21221** [comment]
Send some screenshot if available regarding the ui

**Comment by Git21221** [comment]
I think you made a basic signin signup page for users with authentication...a fullstack MERN

**Comment by Samihan15** [comment]
[https://drive.google.com/drive/folders/1g5CYKfMnrJR-bEA6obczU0tJjxP2TeCO?usp=drive_link](url)
