### ISSUE TITLE
Credit Card Generator

### ISSUE THREAD

**Issue by vaibhavw12** [Git21221/JS-beginner-projects#126]
This is a calculator application made using html, css and js
I want to contribute this app to the repo
@Git21221 please assign this project to me under hacktoberfest

**Comment by Git21221** [comment]
@vaibhavw12 There is already a calculator app. Can you update the existing one?

**Comment by vaibhavw12** [comment]
okay thanks

**Comment by vaibhavw12** [comment]
Can I contribute credit card generator application made using react.js to this repo

**Comment by Git21221** [comment]
@vaibhavw12 sure go ahead, make a pr with proper screenshot
