### ISSUE TITLE
All projects or folders are not added in `index.html` file, So someone please fix this.

### ISSUE THREAD

**Issue by Git21221** [Git21221/JS-beginner-projects#151]
first person will be assigned to do this

**Comment by parinitapatil** [comment]
Can you assign me to a task, please?

**Comment by Git21221** [comment]
@parinitapatil sure go ahead, waiting your pr to be merged

**Comment by Git21221** [comment]
> Can you assign me to a task, please?

Any update on it?

**Comment by parinitapatil** [comment]
can i give you update till evening?

**Comment by Git21221** [comment]
@parinitapatil sure

**Comment by parinitapatil** [comment]
I have made some updates to the file and would appreciate it if you could review it.
