### ISSUE TITLE
Note Taking web application using HTML, CSS, and JavaScript. 

### ISSUE THREAD

**Issue by priyesh0453** [Git21221/JS-beginner-projects#184]
- **Interactive User Interface**: Design an appealing, user-friendly interface that enhances the note-taking experience.
- **Note Creation**: Implement the ability for users to create new notes with titles and content.
- **Note Deletion**: Allow users to delete individual notes they no longer need.
- **Infinite Note Additions**: Users should be able to add unlimited notes.
- **Favicon Added**

Would love to work on the same and integrate a few more CSS styles for a better experience. Please assign the same @Git21221 if the same can be added to your repo.

**Comment by Git21221** [comment]
@priyesh0453 sure go ahead, make a pr with proper screenshot

**Comment by Priyanshukj02** [comment]
Please assign me also
