### ISSUE TITLE
Pomodoro Timer using HTML, CSS & JS [Hacktoberfest '23]

### ISSUE THREAD

**Issue by priyesh0453** [Git21221/JS-beginner-projects#185]
# Hacktoberfest 2023 Contribution Proposal

## Project Name: Pomodoro Timer

Hello @Git21221,

I am interested in contributing the Pomodoro Timer project to your repository under Hacktoberfest 2023. 

### Proposed Contribution

I would like to work on enhancing the existing Pomodoro Timer project by implementing the following key features:

1. Adding the ability to set custom work and break intervals.
2. Adding looping audios during work and break intervals.
3. Ensuring the timer displays the remaining time dynamically.
4. Improving the user interface for a more interactive experience.

### Teck Stack Planned

I will work on the above-listed features using HTML, CSS, and JavaScript to ensure a fully functional and user-friendly Pomodoro Timer.

### Labels

I propose labeling this issue under the following categories:
- `hacktoberfest`
- `hacktoberfest-accepted`

Consider assigning me to this task.

**Comment by Git21221** [comment]
@priyesh0453 sure go ahead, make a pr with proper screenshot
