### ISSUE TITLE
Feat:Calender Functionality

### ISSUE THREAD

**Issue by zainbinshakoor** [Git21221/JS-beginner-projects#19]
The code creates a basic interactive calendar that allows users to navigate between months. It displays the days of the week. The calendar's design and functionality can be further customized to meet your specific requirements.
Yes. Please assign this to me under hacktoberfest

**Comment by Git21221** [comment]
@zainbinshakoor sure go ahead, make sure to make a pr with proper screenshot.

**Comment by zainbinshakoor** [comment]
GH-34
