### ISSUE TITLE
[NEW GAME] : Emoji Charades

### ISSUE THREAD

**Issue by akhilender-bongirwar** [Git21221/JS-beginner-projects#191]
### Description
- It is a fun game where there will be emojis displayed on the screen and the player needs to enter the suitable word describing the emoji which appears respectively.
### Game points
- The score keeps increasing as the player guesses the correct description of the emoji shown.

- I would like to add this game under the label hacktoberfest2k23

**Comment by Git21221** [comment]
@akhilender-bongirwar sure go ahead, make a pr with proper screenshot.
