### ISSUE TITLE
Adding High Score Feature to Snake Game

### ISSUE THREAD

**Issue by vaishnavibn14** [Git21221/JS-beginner-projects#194]
The snake game currently lacks a high score feature, which is a standard element in most games. Adding a high score functionality will enhance the competitiveness and engagement of players. Users should be able to see their highest achieved score and aim to beat it during each gameplay session

Proposed Solution:
Implement a high score system using JavaScript and, if needed, backend technologies. Store the high score in a persistent data storage solution (e.g., database, local storage, cookies) to ensure it is retained even when the user navigates away from the game or refreshes the page.

Please assign me this issue under Hacktoberfest tag.

**Comment by Git21221** [comment]
@vaishnavibn14 sure go ahead, make a pr with proper screenshot, also it doesn't need to use backend just use localstorage.
