### ISSUE TITLE
snake game lacks a start button

### ISSUE THREAD

**Issue by pranav-jadhav** [Git21221/JS-beginner-projects#195]
Snake Game starts as soon as the page is loaded.

Currently, the snake game lacks a start button, making it difficult for users to initiate the game without any clear instruction. Adding a start button will provide a clear way for users to begin the game, enhancing the user experience.
I would also like to add high score and current score trackers.

Please assign me this issue with HacktoberFest tag.
![Screenshot 2023-10-02 235108](https://github.com/Git21221/JS-beginner-projects/assets/69238138/2cc41eac-04fd-4086-8545-9b9383c82827)

**Comment by Git21221** [comment]
@pranav-jadhav Yeah a start button is necessary, also whenever the game lose replace the alert with a section below the game screen to start again button. and also reduce the speed of snake a bit.
