### ISSUE TITLE
[Github Dev Finder] : Display Alert Box for Missing Username or invalid username 

### ISSUE THREAD

**Issue by pranav-jadhav** [Git21221/JS-beginner-projects#197]
### Issue

Currently, the application does not handle the case where a user does not enter a username. This can lead to unexpected behavior or errors in the application flow. To improve user experience and provide clear feedback, we need to implement a mechanism to display an alert box when the user attempts to proceed without entering a username.

### Proposed Solution

Implement JavaScript validation to check if the username input field is empty when the form is submitted. If it is empty, display an alert box with a message indicating that a username is required. 

Please assign me this issue under Hacktober Fest tag.

![image](https://github.com/Git21221/JS-beginner-projects/assets/69238138/65cc982c-1e68-4fa8-90b2-3968a6d623f6)

**Comment by Git21221** [comment]
@pranav-jadhav sure go ahead, make a pr with proper screenshot.
