### ISSUE TITLE
[Movie App] Changing Movie App UI

### ISSUE THREAD

**Issue by pranav-jadhav** [Git21221/JS-beginner-projects#198]
Summary:
The current user interface of the movie app needs to be updated to enhance its visual appeal, user experience, and overall usability. 

Proposed UI Changes:
Changing Layout of Navbar to make it look visually appealing.

Please Assign this issue under Hacktober Fest tag.

![image](https://github.com/Git21221/JS-beginner-projects/assets/69238138/8cc24e06-8d64-44b3-9bc4-f043413073c8)

**Comment by Git21221** [comment]
@pranav-jadhav sure go ahead, make a pr with proper screenshot.

**Comment by Git21221** [comment]
@vaishnavibn14 It's a first come first serve so if he doesn't make it within 3days then it will be assigned to you.
