### ISSUE TITLE
[JAVASCRIPT PAIRS GAME]: Add Start and Restart Game Buttons.

### ISSUE THREAD

**Issue by vaishnavibn14** [Git21221/JS-beginner-projects#200]
I'd like to add "Start" and "Restart" buttons to our game to enhance user experience. These buttons should be prominently displayed on the game interface. The "Start" button should initiate the game, while the "Restart" button should reset the game to its initial state.

Please assign me this issue under HacktoberFest tag.

![image](https://github.com/Git21221/JS-beginner-projects/assets/75124124/b1eefd8b-b6e4-484b-918f-6a6a828dfe15)

**Comment by Git21221** [comment]
@vaishnavibn14 sure go ahead, make a pr with proper screenshot.
