### ISSUE TITLE
[JAVASCRIPT PAIRS GAME]: Add Winning Message Alert Box.

### ISSUE THREAD

**Issue by vaishnavibn14** [Git21221/JS-beginner-projects#201]
I'd like to add a winning message alert box that appears when a user completes the game successfully. 

Proposed Solution: 

Create a Function to Display the Alert Box. 

Please assign me this issue under HacktoberFest tag.

![image](https://github.com/Git21221/JS-beginner-projects/assets/75124124/42913d36-e9f4-49eb-9a4a-32fbae97e0ee)

**Comment by Git21221** [comment]
@vaishnavibn14 No need to create a alert box. just make a section below game that says winner and also a start, restart btns
