### ISSUE TITLE
CSS Styling Issue in Password Generator

### ISSUE THREAD

**Issue by vaishnavibn14** [Git21221/JS-beginner-projects#203]
**Issue Description:**
I would like to add CSS styling to the Password Generator project. The web page doesn't display as expected.

**Expected Behavior:**
The Password Generator web page should display with the CSS styles applied correctly, providing a visually appealing and user-friendly interface.

Please assign me this issue under HacktoberFest tag.

![image](https://github.com/Git21221/JS-beginner-projects/assets/75124124/307b0e5e-ef2e-4bf9-838b-8a17968e36c9)

**Comment by Git21221** [comment]
@vaishnavibn14 I think the functionality is not working as expected. Can you change that too? make a pr with proper screenshot.
