### ISSUE TITLE
Adding Functionality to Generate Password Button and Copy to Clipboard button in Random Password Generator

### ISSUE THREAD

**Issue by pranav-jadhav** [Git21221/JS-beginner-projects#204]
![image](https://github.com/Git21221/JS-beginner-projects/assets/69238138/29b42cd3-ea93-45c3-a28e-a13355f84773)

Currently Nothing happens when generate password button is clicked. 

I would like implement this functionality.

Please assign me this issue under the HacktoberFest tag

**Comment by Git21221** [comment]
@pranav-jadhav sure go ahead, make a pr with proper screenshot.

**Comment by uzair-ahmed-01** [comment]
It already had this feature, but I saw that there was a problem when importing the CSS and JS files. Once that was resolved, all of the functionality was usable.  @Git21221
