### ISSUE TITLE
Navbar brand text not working properly

### ISSUE THREAD

**Issue by muhammadnaeemtahir** [Git21221/JS-beginner-projects#231]
[screen-capture (1).webm](https://github.com/Git21221/JS-beginner-projects/assets/95528641/5efe82d0-f3ed-4e51-a4ec-2838032c6bd4)

You can see here the bug

**Comment by Git21221** [comment]
@muhammadnaeemtahir start working on it, and make a pr with proper screenshot

**Comment by muhammadnaeemtahir** [comment]
Alright, I am on it
