### ISSUE TITLE
Cryptocurrency Price Tracker [HTML, CSS, JS & API]

### ISSUE THREAD

**Issue by priyesh0453** [Git21221/JS-beginner-projects#234]
# Hacktoberfest 2023 Contribution Proposal

## Project Name: Cryptocurrency Price Tracker

Hello @Git21221,

I am interested in contributing to the Cryptocurrency Price Tracker project in your repository for Hacktoberfest 2023.

### Proposed Contribution

I would like to work on enhancing the Cryptocurrency Price Tracker project by implementing the following key features:

1. **User Interface Enhancements**: User-friendly and visually appealing.

2. **Real-Time Price**: Of the top 11 Cryptocurrencies by market capitalization. Additionally, color-coded for drops and rises. Updated frequently.  

3. **Interactive CSS effects and UI**: Favicons, Interactive Tabulations, Title, and much more...

### Tech Stack

HTML, CSS, and JavaScript to ensure a fully functional and user-friendly Cryptocurrency Price Tracker.

### Labels

I suggest labeling this issue under the following categories:
- `hacktoberfest`
- `hacktoberfest-accepted`

Please consider assigning me to this task.

I look forward to contributing to this project.

Thank you!
Priyesh Mishra ( @priyesh0453 )

**Comment by Git21221** [comment]
@priyesh0453 sure go ahead, make a pr with proper screenshot.
