### ISSUE TITLE
Design Dragon game

### ISSUE THREAD

**Issue by Kumarabhi0776** [Git21221/JS-beginner-projects#246]
“Dragon’s World” is a game in which one dragon tries to save itself from the other dragon by jumping over the dragon which comes in its way. The score is updated when one dragon saves himself from the other dragon. 

I will make this game using HTML , CSS, JS.  Kindly allow me @Git21221

**Comment by Git21221** [comment]
@Kumarabhi0776 sure go ahead, make a pr with proper screenshot.
