### ISSUE TITLE
Solving Big Branding Issue: Enhancing UI/UX of Text-to-Speech App

### ISSUE THREAD

**Issue by PratikKrGhosh** [Git21221/JS-beginner-projects#295]
### I want to enhance the UI of Text to Speech app as it is different from the main and other pages of this website which is not good for Branding.

![Screenshot 2023-10-11 015236](https://github.com/Git21221/JS-beginner-projects/assets/144181107/286429a7-d90e-4518-80a5-09df2cd0f834)

**Comment by PratikKrGhosh** [comment]
This is not a small issue. **This page does not follow neither The Color Scheme nor the design style** which is a Big Issue for _Branding_. I want to work on this Issue. 

> Please Assign me for this issue

**Comment by Git21221** [comment]
@PratikKrGhosh sure go ahead.
