### ISSUE TITLE
Enhance-Ui-Timmer 

### ISSUE THREAD

**Issue by zainbinshakoor** [Git21221/JS-beginner-projects#4]
![image](https://github.com/Git21221/JS-beginner-projects/assets/92578770/e55cb855-01fe-4a3f-8f4e-83e6031707a4)
Yes. Please assign this to me

**Comment by Git21221** [comment]
@zainbinshakoor sure go ahead, make a pr with proper screenshot

**Comment by zainbinshakoor** [comment]
@Git21221  I would appreciate it if you could take the time to review my pull request (PR). Your feedback and approval on the PR would be greatly valued and helpful to me. Thank you
