### ISSUE TITLE
add Drum Kit 

### ISSUE THREAD

**Issue by TeaByte** [Git21221/JS-beginner-projects#89]
if possible please give tag of hacktoberfest to it and assign this to me

**Comment by TeaByte** [comment]
https://github.com/Git21221/JS-beginner-projects/pull/88

**Comment by Git21221** [comment]
@TeaByte sure go ahead, Make a pr with proper screenshot

**Comment by TeaByte** [comment]
> @TeaByte sure go ahead, Make a pr with proper screenshot

already done https://github.com/Git21221/JS-beginner-projects/pull/88
