### ISSUE TITLE
Make a section on navbar named "contributor" and add all the contributers with thanks giving.

### ISSUE THREAD

**Issue by Git21221** [Git21221/JS-beginner-projects#94]
Anyone is free to work on this...use discussion section to communicate with each contributor.

**Comment by Abhishekvermaa** [comment]
pls assign this issue to me !

**Comment by m-shazaib** [comment]
Adding only the contributor section will not be visually appealing in terms of user experience. Can we make a whole navbar consisting different sections including Projects, Repository link, Contributor.
You can see only contributor section isn't looking fine.
![image](https://github.com/Git21221/JS-beginner-projects/assets/111436809/64f84d06-dc9b-4942-8244-12888437d433)

**Comment by Git21221** [comment]
@Abhishekvermaa && @m-shazaib both work on this. if you need to make a new landing page design then do it. just make it look good.

**Comment by uzair-ahmed-01** [comment]
i want to do it can assign it to me

**Comment by Git21221** [comment]
The best work will be merged

**Comment by uzair-ahmed-01** [comment]
In addition to redesigning the landing page and making it responsive, I also included a Contributors button next to the github button and changed the font family of the H1 tags to make them more eye-catching.

How is that?? @Git21221 
can i make a pull request ????

![screenshot-127 0 0 1_5500-2023 10 03-02_27_15](https://github.com/Git21221/JS-beginner-projects/assets/46860228/f0f3979c-0866-442c-854a-112a6bee5314)

**Comment by uzair-ahmed-01** [comment]
Responsive Design

![Mobile](https://github.com/Git21221/JS-beginner-projects/assets/46860228/5b13f0b5-944a-43b4-be4e-31fed0dd46d2)

**Comment by Git21221** [comment]
@uzair-ahmed-01 make a pr...Nice UI btw.

**Comment by m-shazaib** [comment]
hey how about this
![image](https://github.com/Git21221/JS-beginner-projects/assets/111436809/f4ab646c-d86d-46dc-9eb0-6fa4cf08362d)
and the contributor section
![image](https://github.com/Git21221/JS-beginner-projects/assets/111436809/d4be9c64-4931-49f5-9683-55ae986bbae1)
and its responsive too
![image](https://github.com/Git21221/JS-beginner-projects/assets/111436809/d72a4f1d-f1bd-47ec-86b3-158483da5679)

**Comment by Git21221** [comment]
@Abhishekvermaa Contributor's name and profile should have some more space.

**Comment by m-shazaib** [comment]
alright I will add spacing

**Comment by m-shazaib** [comment]
what about now?
large screens
![image](https://github.com/Git21221/JS-beginner-projects/assets/111436809/30d7c3ea-28cb-498e-8984-42c1bbc1fa99)
small screens
![image](https://github.com/Git21221/JS-beginner-projects/assets/111436809/2357179b-ec59-4e5f-8f75-5d48b0e19b06)

**Comment by Git21221** [comment]
@m-shazaib ok make a pr

**Comment by uzair-ahmed-01** [comment]
> @uzair-ahmed-01 make a pr...Nice UI btw.

Thanx 😄 Is that anything else you want me to change or make something different on response side.

**Comment by uzair-ahmed-01** [comment]
What PR will raise if i create a complete landing page? For example, the current issue is #94, but I've made numerous adjustments, so please create a new issue with a landing page so I may raise my PR on that problem. Or i make PR on this issue???@Git21221

**Comment by uzair-ahmed-01** [comment]
@Git21221 can you open the issue so ill solved it you can see landing poge its UI breaking from everywhere
